/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlanoAcaoRouteImport } from './routes/plano-acao'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ParaProfissionaisRouteImport } from './routes/para-profissionais'
import { Route as ParaPacientesRouteImport } from './routes/para-pacientes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as MeuRiscoRouteImport } from './routes/meu-risco'
import { Route as MedicoRouteImport } from './routes/medico'
import { Route as MedicamentosRouteImport } from './routes/medicamentos'
import { Route as LerExameRouteImport } from './routes/ler-exame'
import { Route as HtcareAdminRouteImport } from './routes/htcare-admin'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ExamesRouteImport } from './routes/exames'
import { Route as DesafioRouteImport } from './routes/desafio'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Protocolo90DiasIdRouteImport } from './routes/protocolo-90-dias.$id'
import { Route as PerfilSectionRouteImport } from './routes/perfil.$section'
import { Route as ExameResultadoIdRouteImport } from './routes/exame-resultado.$id'
import { Route as AdminMedicoRouteImport } from './routes/admin.medico'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPacientesIndexRouteImport } from './routes/_authenticated/pacientes.index'
import { Route as AuthenticatedPacientesIdRouteImport } from './routes/_authenticated/pacientes.$id'
import { Route as AuthenticatedPacienteDashboardIdRouteImport } from './routes/_authenticated/paciente-dashboard.$id'
import { Route as AuthenticatedCheckinPatientIdRouteImport } from './routes/_authenticated/checkin.$patientId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoAcaoRoute = PlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaProfissionaisRoute = ParaProfissionaisRouteImport.update({
  id: '/para-profissionais',
  path: '/para-profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaPacientesRoute = ParaPacientesRouteImport.update({
  id: '/para-pacientes',
  path: '/para-pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuRiscoRoute = MeuRiscoRouteImport.update({
  id: '/meu-risco',
  path: '/meu-risco',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicoRoute = MedicoRouteImport.update({
  id: '/medico',
  path: '/medico',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentosRoute = MedicamentosRouteImport.update({
  id: '/medicamentos',
  path: '/medicamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LerExameRoute = LerExameRouteImport.update({
  id: '/ler-exame',
  path: '/ler-exame',
  getParentRoute: () => rootRouteImport,
} as any)
const HtcareAdminRoute = HtcareAdminRouteImport.update({
  id: '/htcare-admin',
  path: '/htcare-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesRoute = ExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafioRoute = DesafioRouteImport.update({
  id: '/desafio',
  path: '/desafio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Protocolo90DiasIdRoute = Protocolo90DiasIdRouteImport.update({
  id: '/protocolo-90-dias/$id',
  path: '/protocolo-90-dias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilSectionRoute = PerfilSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PerfilRoute,
} as any)
const ExameResultadoIdRoute = ExameResultadoIdRouteImport.update({
  id: '/exame-resultado/$id',
  path: '/exame-resultado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMedicoRoute = AdminMedicoRouteImport.update({
  id: '/admin/medico',
  path: '/admin/medico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesIndexRoute =
  AuthenticatedPacientesIndexRouteImport.update({
    id: '/pacientes/',
    path: '/pacientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacientesIdRoute =
  AuthenticatedPacientesIdRouteImport.update({
    id: '/pacientes/$id',
    path: '/pacientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacienteDashboardIdRoute =
  AuthenticatedPacienteDashboardIdRouteImport.update({
    id: '/paciente-dashboard/$id',
    path: '/paciente-dashboard/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckinPatientIdRoute =
  AuthenticatedCheckinPatientIdRouteImport.update({
    id: '/checkin/$patientId',
    path: '/checkin/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/conquistas': typeof ConquistasRoute
  '/desafio': typeof DesafioRoute
  '/exames': typeof ExamesRoute
  '/historico': typeof HistoricoRoute
  '/htcare-admin': typeof HtcareAdminRoute
  '/ler-exame': typeof LerExameRoute
  '/medicamentos': typeof MedicamentosRoute
  '/medico': typeof MedicoRoute
  '/meu-risco': typeof MeuRiscoRoute
  '/missoes': typeof MissoesRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/para-pacientes': typeof ParaPacientesRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/plano-acao': typeof PlanoAcaoRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/admin/medico': typeof AdminMedicoRoute
  '/exame-resultado/$id': typeof ExameResultadoIdRoute
  '/perfil/$section': typeof PerfilSectionRoute
  '/protocolo-90-dias/$id': typeof Protocolo90DiasIdRoute
  '/checkin/$patientId': typeof AuthenticatedCheckinPatientIdRoute
  '/paciente-dashboard/$id': typeof AuthenticatedPacienteDashboardIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/conquistas': typeof ConquistasRoute
  '/desafio': typeof DesafioRoute
  '/exames': typeof ExamesRoute
  '/historico': typeof HistoricoRoute
  '/htcare-admin': typeof HtcareAdminRoute
  '/ler-exame': typeof LerExameRoute
  '/medicamentos': typeof MedicamentosRoute
  '/medico': typeof MedicoRoute
  '/meu-risco': typeof MeuRiscoRoute
  '/missoes': typeof MissoesRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/para-pacientes': typeof ParaPacientesRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/plano-acao': typeof PlanoAcaoRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/admin/medico': typeof AdminMedicoRoute
  '/exame-resultado/$id': typeof ExameResultadoIdRoute
  '/perfil/$section': typeof PerfilSectionRoute
  '/protocolo-90-dias/$id': typeof Protocolo90DiasIdRoute
  '/checkin/$patientId': typeof AuthenticatedCheckinPatientIdRoute
  '/paciente-dashboard/$id': typeof AuthenticatedPacienteDashboardIdRoute
  '/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/pacientes': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/conquistas': typeof ConquistasRoute
  '/desafio': typeof DesafioRoute
  '/exames': typeof ExamesRoute
  '/historico': typeof HistoricoRoute
  '/htcare-admin': typeof HtcareAdminRoute
  '/ler-exame': typeof LerExameRoute
  '/medicamentos': typeof MedicamentosRoute
  '/medico': typeof MedicoRoute
  '/meu-risco': typeof MeuRiscoRoute
  '/missoes': typeof MissoesRoute
  '/onboarding': typeof OnboardingRoute
  '/painel': typeof PainelRoute
  '/para-pacientes': typeof ParaPacientesRoute
  '/para-profissionais': typeof ParaProfissionaisRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/plano-acao': typeof PlanoAcaoRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/relatorio': typeof RelatorioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/admin/medico': typeof AdminMedicoRoute
  '/exame-resultado/$id': typeof ExameResultadoIdRoute
  '/perfil/$section': typeof PerfilSectionRoute
  '/protocolo-90-dias/$id': typeof Protocolo90DiasIdRoute
  '/_authenticated/checkin/$patientId': typeof AuthenticatedCheckinPatientIdRoute
  '/_authenticated/paciente-dashboard/$id': typeof AuthenticatedPacienteDashboardIdRoute
  '/_authenticated/pacientes/$id': typeof AuthenticatedPacientesIdRoute
  '/_authenticated/pacientes/': typeof AuthenticatedPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check-in'
    | '/conquistas'
    | '/desafio'
    | '/exames'
    | '/historico'
    | '/htcare-admin'
    | '/ler-exame'
    | '/medicamentos'
    | '/medico'
    | '/meu-risco'
    | '/missoes'
    | '/onboarding'
    | '/painel'
    | '/para-pacientes'
    | '/para-profissionais'
    | '/perfil'
    | '/plano-acao'
    | '/planos'
    | '/privacidade'
    | '/relatorio'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profissionais'
    | '/admin/medico'
    | '/exame-resultado/$id'
    | '/perfil/$section'
    | '/protocolo-90-dias/$id'
    | '/checkin/$patientId'
    | '/paciente-dashboard/$id'
    | '/pacientes/$id'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check-in'
    | '/conquistas'
    | '/desafio'
    | '/exames'
    | '/historico'
    | '/htcare-admin'
    | '/ler-exame'
    | '/medicamentos'
    | '/medico'
    | '/meu-risco'
    | '/missoes'
    | '/onboarding'
    | '/painel'
    | '/para-pacientes'
    | '/para-profissionais'
    | '/perfil'
    | '/plano-acao'
    | '/planos'
    | '/privacidade'
    | '/relatorio'
    | '/sitemap.xml'
    | '/dashboard'
    | '/profissionais'
    | '/admin/medico'
    | '/exame-resultado/$id'
    | '/perfil/$section'
    | '/protocolo-90-dias/$id'
    | '/checkin/$patientId'
    | '/paciente-dashboard/$id'
    | '/pacientes/$id'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/check-in'
    | '/conquistas'
    | '/desafio'
    | '/exames'
    | '/historico'
    | '/htcare-admin'
    | '/ler-exame'
    | '/medicamentos'
    | '/medico'
    | '/meu-risco'
    | '/missoes'
    | '/onboarding'
    | '/painel'
    | '/para-pacientes'
    | '/para-profissionais'
    | '/perfil'
    | '/plano-acao'
    | '/planos'
    | '/privacidade'
    | '/relatorio'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/profissionais'
    | '/admin/medico'
    | '/exame-resultado/$id'
    | '/perfil/$section'
    | '/protocolo-90-dias/$id'
    | '/_authenticated/checkin/$patientId'
    | '/_authenticated/paciente-dashboard/$id'
    | '/_authenticated/pacientes/$id'
    | '/_authenticated/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckInRoute: typeof CheckInRoute
  ConquistasRoute: typeof ConquistasRoute
  DesafioRoute: typeof DesafioRoute
  ExamesRoute: typeof ExamesRoute
  HistoricoRoute: typeof HistoricoRoute
  HtcareAdminRoute: typeof HtcareAdminRoute
  LerExameRoute: typeof LerExameRoute
  MedicamentosRoute: typeof MedicamentosRoute
  MedicoRoute: typeof MedicoRoute
  MeuRiscoRoute: typeof MeuRiscoRoute
  MissoesRoute: typeof MissoesRoute
  OnboardingRoute: typeof OnboardingRoute
  PainelRoute: typeof PainelRoute
  ParaPacientesRoute: typeof ParaPacientesRoute
  ParaProfissionaisRoute: typeof ParaProfissionaisRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  PlanoAcaoRoute: typeof PlanoAcaoRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RelatorioRoute: typeof RelatorioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminMedicoRoute: typeof AdminMedicoRoute
  ExameResultadoIdRoute: typeof ExameResultadoIdRoute
  Protocolo90DiasIdRoute: typeof Protocolo90DiasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-acao': {
      id: '/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof PlanoAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-profissionais': {
      id: '/para-profissionais'
      path: '/para-profissionais'
      fullPath: '/para-profissionais'
      preLoaderRoute: typeof ParaProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-pacientes': {
      id: '/para-pacientes'
      path: '/para-pacientes'
      fullPath: '/para-pacientes'
      preLoaderRoute: typeof ParaPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-risco': {
      id: '/meu-risco'
      path: '/meu-risco'
      fullPath: '/meu-risco'
      preLoaderRoute: typeof MeuRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medico': {
      id: '/medico'
      path: '/medico'
      fullPath: '/medico'
      preLoaderRoute: typeof MedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicamentos': {
      id: '/medicamentos'
      path: '/medicamentos'
      fullPath: '/medicamentos'
      preLoaderRoute: typeof MedicamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler-exame': {
      id: '/ler-exame'
      path: '/ler-exame'
      fullPath: '/ler-exame'
      preLoaderRoute: typeof LerExameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/htcare-admin': {
      id: '/htcare-admin'
      path: '/htcare-admin'
      fullPath: '/htcare-admin'
      preLoaderRoute: typeof HtcareAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames': {
      id: '/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof ExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafio': {
      id: '/desafio'
      path: '/desafio'
      fullPath: '/desafio'
      preLoaderRoute: typeof DesafioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo-90-dias/$id': {
      id: '/protocolo-90-dias/$id'
      path: '/protocolo-90-dias/$id'
      fullPath: '/protocolo-90-dias/$id'
      preLoaderRoute: typeof Protocolo90DiasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$section': {
      id: '/perfil/$section'
      path: '/$section'
      fullPath: '/perfil/$section'
      preLoaderRoute: typeof PerfilSectionRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/exame-resultado/$id': {
      id: '/exame-resultado/$id'
      path: '/exame-resultado/$id'
      fullPath: '/exame-resultado/$id'
      preLoaderRoute: typeof ExameResultadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/medico': {
      id: '/admin/medico'
      path: '/admin/medico'
      fullPath: '/admin/medico'
      preLoaderRoute: typeof AdminMedicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/': {
      id: '/_authenticated/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof AuthenticatedPacientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes/$id': {
      id: '/_authenticated/pacientes/$id'
      path: '/pacientes/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof AuthenticatedPacientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paciente-dashboard/$id': {
      id: '/_authenticated/paciente-dashboard/$id'
      path: '/paciente-dashboard/$id'
      fullPath: '/paciente-dashboard/$id'
      preLoaderRoute: typeof AuthenticatedPacienteDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin/$patientId': {
      id: '/_authenticated/checkin/$patientId'
      path: '/checkin/$patientId'
      fullPath: '/checkin/$patientId'
      preLoaderRoute: typeof AuthenticatedCheckinPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedCheckinPatientIdRoute: typeof AuthenticatedCheckinPatientIdRoute
  AuthenticatedPacienteDashboardIdRoute: typeof AuthenticatedPacienteDashboardIdRoute
  AuthenticatedPacientesIdRoute: typeof AuthenticatedPacientesIdRoute
  AuthenticatedPacientesIndexRoute: typeof AuthenticatedPacientesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedCheckinPatientIdRoute: AuthenticatedCheckinPatientIdRoute,
  AuthenticatedPacienteDashboardIdRoute: AuthenticatedPacienteDashboardIdRoute,
  AuthenticatedPacientesIdRoute: AuthenticatedPacientesIdRoute,
  AuthenticatedPacientesIndexRoute: AuthenticatedPacientesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PerfilRouteChildren {
  PerfilSectionRoute: typeof PerfilSectionRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilSectionRoute: PerfilSectionRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckInRoute: CheckInRoute,
  ConquistasRoute: ConquistasRoute,
  DesafioRoute: DesafioRoute,
  ExamesRoute: ExamesRoute,
  HistoricoRoute: HistoricoRoute,
  HtcareAdminRoute: HtcareAdminRoute,
  LerExameRoute: LerExameRoute,
  MedicamentosRoute: MedicamentosRoute,
  MedicoRoute: MedicoRoute,
  MeuRiscoRoute: MeuRiscoRoute,
  MissoesRoute: MissoesRoute,
  OnboardingRoute: OnboardingRoute,
  PainelRoute: PainelRoute,
  ParaPacientesRoute: ParaPacientesRoute,
  ParaProfissionaisRoute: ParaProfissionaisRoute,
  PerfilRoute: PerfilRouteWithChildren,
  PlanoAcaoRoute: PlanoAcaoRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RelatorioRoute: RelatorioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminMedicoRoute: AdminMedicoRoute,
  ExameResultadoIdRoute: ExameResultadoIdRoute,
  Protocolo90DiasIdRoute: Protocolo90DiasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
